### ISSUE TITLE
feat: Upload package to pub.dev

### ISSUE THREAD

**Issue by Shamsudeen12** [manuelperez96/google_places_dialog#2]
**Description**

Are you going to upload this package to pub.dev?

**Comment by manuelperez96** [comment]
Could be an option in the Future. I never think about it, because I developed this project for my work. For now, I dont think so.

**Comment by Shamsudeen12** [comment]
Yeah, I was just thinking, cuz there aren't good alternatives on pub.dev 
If you can upload it, I'll be part of the maintainers

**Comment by manuelperez96** [comment]
I think about it. I never upload any package, so I am going to need some time to do it.

**Comment by Shamsudeen12** [comment]
No problem. Let me know what you decide

**Comment by Shamsudeen12** [comment]
If not, I can upload it with your permission

**Comment by manuelperez96** [comment]
The package is uploaded. 

https://pub.dev/packages/google_places_dialog.

I like how you rename the package, so I took that name ^^.

**Comment by Shamsudeen12** [comment]
Great. Thank you @manuelperez96 
So I'll use the pub.dev link instead of the github one
